services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 512M
  web:
    build: .
    ports:
      - "8066:80"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
