services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
  web:
    build: .
    ports:
      - "8066:80"
    environment:
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    depends_on:
      - db
